var template = require('template')

template.templates = {
	'chatheader.jade': require('./chatheader.jade'),
	'rightsidebar.jade': require('./rightsidebar.jade'),
	'uploads.jade': require('./uploads.jade'),
	'roommembers.jade': require('./roommembers.jade'),
	'chathistory.jade': require('./chathistory.jade'),
	'dialogs/deleteroom.jade': require('./dialogs/deleteroom.jade'),
	'dialogs/invite.jade': require('./dialogs/invite.jade'),
	'dialogs/markdowntips.jade': require('./dialogs/markdowntips.jade'),
	'dialogs/menu.jade': require('./dialogs/menu.jade'),
	'dialogs/pmlist.jade': require('./dialogs/pmlist.jade'),
	'dialogs/pmmanager.jade': require('./dialogs/pmmanager.jade'),
	'dialogs/room-creation-form.jade': require('./dialogs/room-creation-form.jade'),
	'dialogs/roomlist.jade': require('./dialogs/roomlist.jade'),
	'dialogs/roommanager.jade': require('./dialogs/roommanager.jade'),
	'draganddrop.jade': require('./draganddrop.jade'),
	'fileuploader.jade': require('./fileuploader.jade'),
	'grapeinputintegration.jade': require('./grapeinputintegration.jade'),
	'index.jade': require('./index.jade'),
	'messages.jade': require('./messages.jade'),
	'navigation.jade': require('./navigation.jade'),
	'pmlist.jade': require('./pmlist.jade'),
	'pmlist-collapsed.jade': require('./pmlist-collapsed.jade'),
	'popovers/organization.jade': require('./popovers/organization.jade'),
	'popovers/pmmanager.jade': require('./popovers/pmmanager.jade'),
	'popovers/pmlist.jade': require('./popovers/pmlist.jade'),
	'popovers/user.jade': require('./popovers/user.jade'),
	'roomlist.jade': require('./roomlist.jade'),
	'roomlist-collapsed.jade': require('./roomlist-collapsed.jade'),
	'searchresults.jade': require('./searchresults.jade'),
	'typingnotifications.jade': require('./typingnotifications.jade')
}
