export const SET_ORG = 'SET_ORG'
export const SET_USER = 'SET_USER'

export const SHOW_CHANNEL_SEARCH = 'SHOW_CHANNEL_SEARCH'
export const HIDE_CHANNEL_SEARCH = 'HIDE_CHANNEL_SEARCH'
export const INPUT_CHANNEL_SEARCH = 'INPUT_CHANNEL_SEARCH'

export const HIDE_SUBSCRIPTION_WARNING = 'HIDE_SUBSCRIPTION_WARNING'
export const GO_TO_PAYMENT = 'GO_TO_PAYMENT'
