export const NOOP = 'NOOP'

export const SET_ORG = 'SET_ORG'
export const SET_USERS = 'SET_USERS'
export const SET_CHANNELS = 'SET_CHANNELS'
export const SET_ROOMS = 'SET_ROOMS'
export const SET_PMS = 'SET_PMS'
export const INITIAL_DATA_LOADED = 'INITIAL_DATA_LOADED'

export const SET_USER = 'SET_USER'
export const SET_CHANNEL = 'SET_CHANNEL'

export const SET_SETTINGS = 'SET_SETTINGS'
export const SET_SIDEBAR_IS_LOADING = 'SET_SIDEBAR_IS_LOADING'

export const UPDATE_USER = 'UPDATE_USER'
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'

export const ADD_USER_TO_ORG = 'ADD_USER_TO_ORG'
export const REMOVE_USER_FROM_ORG = 'REMOVE_USER_FROM_ORG'

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'

export const CREATE_NEW_CHANNEL = 'CREATE_NEW_CHANNEL'
export const MARK_CHANNEL_AS_READ = 'MARK_CHANNEL_AS_READ'
export const GO_TO_MESSAGE = 'GO_TO_MESSAGE'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'
export const REMOVE_ROOM = 'REMOVE_ROOM'

export const HANDLE_ERROR = 'HANDLE_ERROR'

export const AUTH_ERROR = 'AUTH_ERROR'
export const CONNECTION_ERROR = 'CONNECTION_ERROR'

export const SHOW_CHANNEL_SEARCH = 'SHOW_CHANNEL_SEARCH'
export const HIDE_CHANNEL_SEARCH = 'HIDE_CHANNEL_SEARCH'
export const INPUT_CHANNEL_SEARCH = 'INPUT_CHANNEL_SEARCH'
export const FOCUS_CHANNEL_SEARCH_ITEM = 'FOCUS_CHANNEL_SEARCH_ITEM'
export const SELECT_CHANNEL_SEARCH_ITEM = 'SELECT_CHANNEL_SEARCH_ITEM'

export const SHOW_BILLING_WARNING = 'SHOW_BILLING_WARNING'
export const HIDE_BILLING_WARNING = 'HIDE_BILLING_WARNING'
export const GO_TO_PAYMENT = 'GO_TO_PAYMENT'

export const SET_TYPING_USERS = 'SET_TYPING_USERS'

export const SHOW_USER_PROFILE = 'SHOW_USER_PROFILE'
export const HIDE_USER_PROFILE = 'HIDE_USER_PROFILE'

export const SHOW_CHANNEL_INFO = 'SHOW_CHANNEL_INFO'
export const HIDE_CHANNEL_INFO = 'HIDE_CHANNEL_INFO'
export const LEAVE_CHANNEL = 'LEAVE_CHANNEL'
export const GO_TO_CHANNEL = 'GO_TO_CHANNEL'
export const KICK_MEMBER_FROM_CHANNEL = 'KICK_MEMBER_FROM_CHANNEL'
export const ADD_USER_TO_CHANNEL = 'ADD_USER_TO_CHANNEL'
export const REMOVE_USER_FROM_CHANNEL = 'REMOVE_USER_FROM_CHANNEL'

export const SHOW_CHANNEL_MEMBERS_INVITE = 'SHOW_CHANNEL_MEMBERS_INVITE'
export const HIDE_CHANNEL_MEMBERS_INVITE = 'HIDE_CHANNEL_MEMBERS_INVITE'
export const ADD_TO_CHANNEL_MEMBERS_INVITE = 'ADD_TO_INVITE_CHANNEL_MEMBERLIST'
export const REMOVE_FROM_CHANNEL_MEMBERS_INVITE = 'REMOVE_FROM_CHANNEL_MEMBERS_INVITE'
export const FILTER_CHANNEL_MEMBERS_INVITE = 'FILTER_CHANNEL_MEMBERS_INVITE'
export const INVITED_TO_CHANNEL = 'INVITED_TO_CHANNEL'
export const JOINED_CHANNEL = 'JOINED_CHANNEL'

export const SHOW_ORG_INVITE = 'SHOW_ORG_INVITE'

export const SHOW_SHARED_FILES = 'SHOW_SHARED_FILES'
export const HIDE_SHARED_FILES = 'HIDE_SHARED_FILES'
export const LOAD_SHARED_FILES = 'LOAD_SHARED_FILES'
export const LOADED_SHARED_FILES = 'LOADED_SHARED_FILES'
export const ADD_SHARED_FILE = 'ADD_SHARED_FILE'
export const REMOVE_SHARED_FILE = 'REMOVE_SHARED_FILE'

export const SHOW_MENTIONS = 'SHOW_MENTIONS'
export const HIDE_MENTIONS = 'HIDE_MENTIONS'
export const LOAD_MENTIONS = 'LOAD_MENTIONS'
export const LOADED_MENTIONS = 'LOADED_MENTIONS'
export const ADD_MENTION = 'ADD_MENTION'
export const REMOVE_MENTION = 'REMOVE_MENTION'

export const SHOW_MESSAGE_SEARCH = 'SHOW_MESSAGE_SEARCH'
export const HIDE_MESSAGE_SEARCH = 'HIDE_MESSAGE_SEARCH'
export const SEARCH_MESSAGES = 'SEARCH_MESSAGES'
export const UPDATE_MESSAGE_SEARCH_QUERY = 'UPDATE_MESSAGE_SEARCH_QUERY'
export const FOUND_MESSAGES = 'FOUND_MESSAGES'

export const ENABLE_NOTIFICATIONS = 'ENABLE_NOTIFICATIONS'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const TOGGLE_ORG_SETTINGS = 'TOGGLE_ORG_SETTINGS'
export const SHOW_CHANNELS_MANAGER = 'SHOW_CHANNELS_MANAGER'
export const SHOW_PMS_MANAGER = 'SHOW_PMS_MANAGER'

export const UPDATE_MEMBERSHIP = 'UPDATE_MEMBERSHIP'

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'
