export const SET_ORG = 'SET_ORG'
export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const SET_CHANNELS = 'SET_CHANNELS'
export const SET_CHANNEL = 'SET_CHANNEL'
export const SET_SETTINGS = 'SET_SETTINGS'

export const SHOW_CHANNEL_SEARCH = 'SHOW_CHANNEL_SEARCH'
export const HIDE_CHANNEL_SEARCH = 'HIDE_CHANNEL_SEARCH'
export const INPUT_CHANNEL_SEARCH = 'INPUT_CHANNEL_SEARCH'

export const SHOW_BILLING_WARNING = 'SHOW_BILLING_WARNING'
export const HIDE_BILLING_WARNING = 'HIDE_BILLING_WARNING'
export const GO_TO_PAYMENT = 'GO_TO_PAYMENT'

export const SET_TYPING_USERS = 'SET_TYPING_USERS'
