'use strict';

exports.__esModule = true;
var NOOP = 'NOOP';
exports.NOOP = NOOP;
var FOCUS_SEARCH_BROWSER_ITEM = 'FOCUS_SEARCH_BROWSER_ITEM';
exports.FOCUS_SEARCH_BROWSER_ITEM = FOCUS_SEARCH_BROWSER_ITEM;
var CREATE_SEARCH_BROWSER_STATE = 'CREATE_SEARCH_BROWSER_STATE';
exports.CREATE_SEARCH_BROWSER_STATE = CREATE_SEARCH_BROWSER_STATE;