import { zIndex } from '../../../utils/z-index'

export default () => ({
  wrapper: {
    zIndex: zIndex('dialog'),
    position: 'absolute',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    animation: 'appearance 1s ease-in',
  },
  [`@keyframes appearance`]: {
    '0%': {
      opacity: 0,
    },
    '100%': {
      opacity: 1,
    },
  },
  background: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: zIndex('dialog'),
    left: 0,
    top: 0,
    background: '#333',
    opacity: '0.8',
  },
  dialog: {
    minWidth: 360,
    maxWidth: 600,
    background: '#333',
    zIndex: zIndex('dialog'),
    borderRadius: 16,
    display: 'flex',
    flexDirection: 'column',
    position: 'absolute',
  },
  avatar: {
    margin: '50px auto 30px',
    display: 'block',
    position: 'relative',
  },
  image: {
    height: 160,
    width: 160,
    borderRadius: '50%',
  },
  pulse: {
    position: 'absolute',
    width: 176,
    height: 176,
    display: 'block',
    top: -8,
    stroke: '#FFF',
    strokeWidth: 2,
    opacity: 1,
    transformOrigin: '50% 50%',
    animation: 'pulse 5s infinite cubic-bezier(0.6, 0, 0, 0.4)',
  },
  [`@keyframes pulse`]: {
    '0%': {
      strokeWidth: 2,
      strokeOpacity: 1,
      transform: 'scale(1)',
    },
    '50%': {
      strokeWidth: 2,
      strokeOpacity: 1,
      transform: 'scale(0.9)',
    },
    '100%': {
      strokeWidth: 2,
      strokeOpacity: 1,
      transform: 'scale(1)',
    },
  },
  name: {
    padding: [0, 10, 0, 10],
    display: 'block',
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 600,
    lineHeight: '31px',
    color: '#FFF',
  },
  description: {
    padding: [0, 10, 0, 10],
    marginTop: 5,
    display: 'block',
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '25px',
    color: '#FFF',
  },
  descriptionSmall: {
    maxWidth: 360,
  },
  buttons: {
    marginTop: 65,
    marginBottom: 40,
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    height: 64,
  },
  button: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    position: 'absolute',
    borderRadius: '50%',
  },
  reject: {
    width: 48,
    height: 48,
    background: '#FFF',
    left: 40,
  },
  missedIcon: {
    color: '#D4210A',
    width: 32,
    height: 12,
    pointerEvents: 'none',
  },
  accept: {
    width: 64,
    height: 64,
    background: '#6FA300',
    left: '50%',
    transform: 'translateX(-50%)',
  },
  ongoingIcon: {
    color: '#FFF',
    width: 32,
    height: 32,
    pointerEvents: 'none',
  },
  unsupported: {
    marginTop: 25,
    display: 'block',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: '23px',
    color: '#FFF',
  },
  singleButtons: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  replyButton: {
    cursor: 'pointer',
    marginTop: 15,
    marginBottom: 50,
    lineHeight: '23px',
    padding: '5px 16px 4px',
    backgroundColor: '#8F28B3',
    borderRadius: 16,
    color: '#FFF',
  },
  furtherSteps: {
    backgroundColor: '#FFF',
    width: '100%',
    color: '#333',
    fontSize: 13,
    padding: '24px 40px 20px',
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    lineHeight: '23px',
    '& > p:not(:first-child)': {
      lineHeight: '23px',
      fontSize: 13,
      paddingTop: 15,
    },
  },
  text: {
    fontSize: 13,
  },
  blueLink: {
    color: '#274289',
  },
  bold: {
    fontWeight: 900,
  },
})
