// File is generated by bin/emoji, do not edit.
export default [
  {
    name: '100',
    cat: 'other',
    aliases: [],
  },
  {
    name: '1234',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'hash',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'zero',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'one',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'two',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'three',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'four',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'five',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'six',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'seven',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'eight',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'nine',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'copyright',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'registered',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'bangbang',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'interrobang',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'tm',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'information_source',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'left_right_arrow',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_up_down',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_upper_left',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_upper_right',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_lower_right',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_lower_left',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'leftwards_arrow_with_hook',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_right_hook',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'watch',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'hourglass',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fast_forward',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'rewind',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_double_up',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_double_down',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'alarm_clock',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'hourglass_flowing_sand',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'm',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'black_small_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'white_small_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_forward',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_backward',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'white_medium_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'black_medium_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'white_medium_small_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'black_medium_small_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'sunny',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cloud',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'telephone',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ballot_box_with_check',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'umbrella',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'coffee',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'point_up',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'relaxed',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'aries',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'taurus',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'gemini',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'cancer',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'leo',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'virgo',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'libra',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'scorpius',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'sagittarius',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'capricorn',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'aquarius',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'pisces',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'spades',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clubs',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'hearts',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'diamonds',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'hotsprings',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'recycle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'wheelchair',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'anchor',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'warning',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'zap',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'white_circle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'black_circle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'soccer',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'baseball',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'snowman',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'partly_sunny',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'ophiuchus',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'no_entry',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'church',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fountain',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'golf',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sailboat',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tent',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fuelpump',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'scissors',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'white_check_mark',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'airplane',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'envelope',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fist',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'raised_hand',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'v',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'pencil2',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'black_nib',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'heavy_check_mark',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'heavy_multiplication_x',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'sparkles',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'eight_spoked_asterisk',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'eight_pointed_black_star',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'snowflake',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'sparkle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'x',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'negative_squared_cross_mark',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'question',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'grey_question',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'grey_exclamation',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'exclamation',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'heavy_plus_sign',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'heavy_minus_sign',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'heavy_division_sign',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_right',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'curly_loop',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_heading_up',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_heading_down',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_left',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_up',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrow_down',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'black_large_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'white_large_square',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'star',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'o',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'wavy_dash',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'part_alternation_mark',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'congratulations',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'secret',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'mahjong',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'black_joker',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'a',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'b',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'o2',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'parking',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'ab',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'cl',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'cool',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'free',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'id',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'new',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'ng',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'ok',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'sos',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'up',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'vs',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'cn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'de',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'es',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gb',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'it',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'jp',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'us',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ru',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'koko',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'sa',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u7121',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u6307',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u7981',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u7a7a',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u5408',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u6e80',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u6709',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u6708',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u7533',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u5272',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'u55b6',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'ideograph_advantage',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'accept',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'cyclone',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'foggy',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'closed_umbrella',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'night_with_stars',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sunrise_over_mountains',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sunrise',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'city_dusk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'city_sunset',
    cat: 'places',
    aliases: [':city_sunrise:'],
  },
  {
    name: 'rainbow',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'bridge_at_night',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ocean',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'volcano',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'milky_way',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'earth_asia',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'new_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'first_quarter_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'waxing_gibbous_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'full_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'crescent_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'first_quarter_moon_with_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'star2',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'stars',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'chestnut',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'seedling',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'palm_tree',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cactus',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'tulip',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cherry_blossom',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'rose',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'hibiscus',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'sunflower',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'blossom',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'corn',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ear_of_rice',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'herb',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'four_leaf_clover',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'maple_leaf',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'fallen_leaf',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'leaves',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'mushroom',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'tomato',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'eggplant',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'grapes',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'melon',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'watermelon',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tangerine',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'banana',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'pineapple',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'apple',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'green_apple',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'peach',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'cherries',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'strawberry',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'hamburger',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'pizza',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'meat_on_bone',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'poultry_leg',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'rice_cracker',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'rice_ball',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'rice',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'curry',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ramen',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'spaghetti',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bread',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fries',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sweet_potato',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'dango',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'oden',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sushi',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fried_shrimp',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fish_cake',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'icecream',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'shaved_ice',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ice_cream',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'doughnut',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'cookie',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'chocolate_bar',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'candy',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'lollipop',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'custard',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'honey_pot',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'cake',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bento',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'stew',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'egg',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fork_and_knife',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tea',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sake',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'wine_glass',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'cocktail',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tropical_drink',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'beer',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'beers',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ribbon',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'gift',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'birthday',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'jack_o_lantern',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'christmas_tree',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'santa',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fireworks',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sparkler',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'balloon',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tada',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'confetti_ball',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tanabata_tree',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'crossed_flags',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bamboo',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'dolls',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'flags',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'wind_chime',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'rice_scene',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'school_satchel',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mortar_board',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'carousel_horse',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ferris_wheel',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'roller_coaster',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fishing_pole_and_fish',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'microphone',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'movie_camera',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'cinema',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'headphones',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'art',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tophat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'circus_tent',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ticket',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'clapper',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'performing_arts',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'video_game',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'dart',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'slot_machine',
    cat: 'places',
    aliases: [],
  },
  {
    name: '8ball',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'game_die',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bowling',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'flower_playing_cards',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'musical_note',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'notes',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'saxophone',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'guitar',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'musical_keyboard',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'trumpet',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'violin',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'musical_score',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'running_shirt_with_sash',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'tennis',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ski',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'basketball',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'checkered_flag',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'snowboarder',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'runner',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'surfer',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'trophy',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'football',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'swimmer',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'house',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'house_with_garden',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'office',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'post_office',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'hospital',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bank',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'atm',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'hotel',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'love_hotel',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'convenience_store',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'school',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'department_store',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'factory',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'izakaya_lantern',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'japanese_castle',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'european_castle',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'snail',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'snake',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'racehorse',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'sheep',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'monkey',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'chicken',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'boar',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'elephant',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'octopus',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'shell',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'bug',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'ant',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'bee',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'beetle',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'fish',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'tropical_fish',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'blowfish',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'turtle',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'hatching_chick',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'baby_chick',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'hatched_chick',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'bird',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'penguin',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'koala',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'poodle',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'camel',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'dolphin',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'mouse',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cow',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'tiger',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'rabbit',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cat',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'dragon_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'whale',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'horse',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'monkey_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'dog',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'pig',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'frog',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'hamster',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'wolf',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'bear',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'panda_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'pig_nose',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'feet',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'eyes',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'ear',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'nose',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'lips',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'tongue',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'point_up_2',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'point_down',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'point_left',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'point_right',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'punch',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'wave',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'ok_hand',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'thumbsup',
    cat: 'emoticons',
    aliases: [':+1:'],
  },
  {
    name: 'thumbsdown',
    cat: 'emoticons',
    aliases: [':-1:'],
  },
  {
    name: 'clap',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'open_hands',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'crown',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'womans_hat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'eyeglasses',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'necktie',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'shirt',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'jeans',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'dress',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'kimono',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bikini',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'womans_clothes',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'purse',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'handbag',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'pouch',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'mans_shoe',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'athletic_shoe',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'high_heel',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'sandal',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'boot',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'footprints',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bust_in_silhouette',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'boy',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'girl',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'man',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'woman',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'family',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'couple',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'cop',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'dancers',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bride_with_veil',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'person_with_blond_hair',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'man_with_gua_pi_mao',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'man_with_turban',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'older_man',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'older_woman',
    cat: 'emoticons',
    aliases: [':grandma:'],
  },
  {
    name: 'baby',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'construction_worker',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'princess',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'japanese_ogre',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'japanese_goblin',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'ghost',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'angel',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'alien',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'space_invader',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'imp',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'skull',
    cat: 'emoticons',
    aliases: [':skeleton:'],
  },
  {
    name: 'card_index',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'information_desk_person',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'guardsman',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'dancer',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'lipstick',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'nail_care',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'ledger',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'massage',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'notebook',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'haircut',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'notebook_with_decorative_cover',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'barber',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'closed_book',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'syringe',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'book',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'pill',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'green_book',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'kiss',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'blue_book',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'love_letter',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'orange_book',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'ring',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'books',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'gem',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'name_badge',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'couplekiss',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'scroll',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bouquet',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'pencil',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'couple_with_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'telephone_receiver',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'wedding',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pager',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'fax',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'heartbeat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'satellite',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'loudspeaker',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'broken_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'mega',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'outbox_tray',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'two_hearts',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'inbox_tray',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'package',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sparkling_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'e-mail',
    cat: 'objects',
    aliases: [':email:'],
  },
  {
    name: 'incoming_envelope',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'heartpulse',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'envelope_with_arrow',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mailbox_closed',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'cupid',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'mailbox',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'postbox',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'blue_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'newspaper',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'iphone',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'green_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'calling',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'vibration_mode',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'yellow_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'mobile_phone_off',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'signal_strength',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'purple_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'camera',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'video_camera',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'gift_heart',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'tv',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'radio',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'revolving_hearts',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'vhs',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'arrows_clockwise',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'heart_decoration',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'loud_sound',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'battery',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'diamond_shape_with_a_dot_inside',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'electric_plug',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mag',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bulb',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mag_right',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'lock_with_ink_pen',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'anger',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'closed_lock_with_key',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'key',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bomb',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'lock',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'unlock',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'zzz',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bell',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bookmark',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'boom',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'link',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'radio_button',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'sweat_drops',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'back',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'end',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'droplet',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'on',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'soon',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'dash',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'top',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'underage',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'poop',
    cat: 'emoticons',
    aliases: [':shit:', ':hankey:', ':poo:'],
  },
  {
    name: 'keycap_ten',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'muscle',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'capital_abcd',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'abcd',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'dizzy',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'symbols',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'speech_balloon',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'abc',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'fire',
    cat: 'emoticons',
    aliases: [':flame:'],
  },
  {
    name: 'white_flower',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'flashlight',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'wrench',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'hammer',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'nut_and_bolt',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'moneybag',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'knife',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'gun',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'currency_exchange',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'crystal_ball',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'heavy_dollar_sign',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'six_pointed_star',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'credit_card',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'beginner',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'trident',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'yen',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'black_square_button',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'white_square_button',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'dollar',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'red_circle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'large_blue_circle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'money_with_wings',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'large_orange_diamond',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'large_blue_diamond',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'chart',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'small_orange_diamond',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'small_blue_diamond',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'seat',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'small_red_triangle',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'small_red_triangle_down',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'computer',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'arrow_up_small',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'briefcase',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'arrow_down_small',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock1',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'minidisc',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock2',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'floppy_disk',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock3',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'cd',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock4',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'dvd',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock5',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock6',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'file_folder',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock7',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock8',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'open_file_folder',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock9',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock10',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'page_with_curl',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock11',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock12',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'page_facing_up',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mount_fuji',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tokyo_tower',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'date',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'statue_of_liberty',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'japan',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'calendar',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'moyai',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'grin',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'joy',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'smiley',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'chart_with_upwards_trend',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'smile',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'sweat_smile',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'chart_with_downwards_trend',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'laughing',
    cat: 'emoticons',
    aliases: [':satisfied:'],
  },
  {
    name: 'wink',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bar_chart',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'blush',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'yum',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'clipboard',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'relieved',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'heart_eyes',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'pushpin',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'smirk',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'unamused',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'round_pushpin',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sweat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'pensive',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'paperclip',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'confounded',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'kissing_heart',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'straight_ruler',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'kissing_closed_eyes',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'stuck_out_tongue_winking_eye',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'triangular_ruler',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'stuck_out_tongue_closed_eyes',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'disappointed',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bookmark_tabs',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'angry',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'rage',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'cry',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'persevere',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'triumph',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'disappointed_relieved',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'fearful',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'weary',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'sleepy',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'tired_face',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'sob',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'cold_sweat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'scream',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'astonished',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'flushed',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'dizzy_face',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'mask',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'smile_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'joy_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'smiley_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'heart_eyes_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'smirk_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'kissing_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'pouting_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'crying_cat_face',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'scream_cat',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'no_good',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'ok_woman',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'bow',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'see_no_evil',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'hear_no_evil',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'speak_no_evil',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'raising_hand',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'raised_hands',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'person_frowning',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'person_with_pouting_face',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'pray',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'rocket',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'railway_car',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bullettrain_side',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bullettrain_front',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'metro',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'station',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bus',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'busstop',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ambulance',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fire_engine',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'police_car',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'taxi',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'red_car',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'blue_car',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'truck',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ship',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'speedboat',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'traffic_light',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'construction',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'rotating_light',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'triangular_flag_on_post',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'door',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'no_entry_sign',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'smoking',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'no_smoking',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'bike',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'walking',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'mens',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'womens',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'restroom',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'baby_symbol',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'toilet',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'wc',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'bath',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'grinning',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'innocent',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'smiling_imp',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'sunglasses',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'neutral_face',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'expressionless',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'confused',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'kissing',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'kissing_smiling_eyes',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'stuck_out_tongue',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'worried',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'frowning',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'anguished',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'grimacing',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'open_mouth',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'hushed',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'sleeping',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'no_mouth',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'helicopter',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'steam_locomotive',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'train2',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'light_rail',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tram',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'oncoming_bus',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'trolleybus',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'minibus',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'oncoming_police_car',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'oncoming_taxi',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'oncoming_automobile',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'articulated_lorry',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tractor',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'monorail',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mountain_railway',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'suspension_railway',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mountain_cableway',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'aerial_tramway',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'rowboat',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'vertical_traffic_light',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'put_litter_in_its_place',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'do_not_litter',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'potable_water',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'non-potable_water',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'no_bicycles',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'bicyclist',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mountain_bicyclist',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'no_pedestrians',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'children_crossing',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'shower',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'bathtub',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'passport_control',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'customs',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'baggage_claim',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'left_luggage',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'earth_africa',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'earth_americas',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'globe_with_meridians',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'waxing_crescent_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'waning_gibbous_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'last_quarter_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'waning_crescent_moon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'new_moon_with_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'last_quarter_moon_with_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'full_moon_with_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'sun_with_face',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'evergreen_tree',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'deciduous_tree',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'lemon',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'pear',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'baby_bottle',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'horse_racing',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'rugby_football',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'european_post_office',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'rat',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'mouse2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'ox',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'water_buffalo',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cow2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'tiger2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'leopard',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'rabbit2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'cat2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'dragon',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'crocodile',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'whale2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'ram',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'goat',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'rooster',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'dog2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'pig2',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'dromedary_camel',
    cat: 'nature',
    aliases: [],
  },
  {
    name: 'busts_in_silhouette',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'two_men_holding_hands',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'two_women_holding_hands',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'thought_balloon',
    cat: 'emoticons',
    aliases: [],
  },
  {
    name: 'euro',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'pound',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mailbox_with_mail',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mailbox_with_no_mail',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'postal_horn',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'no_mobile_phones',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'twisted_rightwards_arrows',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'repeat',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'repeat_one',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'arrows_counterclockwise',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'low_brightness',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'high_brightness',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'mute',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'sound',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'no_bell',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'microscope',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'telescope',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'clock130',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock230',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock330',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock430',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock530',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock630',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock730',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock830',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock930',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock1030',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock1130',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'clock1230',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'speaker',
    cat: 'objects',
    aliases: [],
  },
  {
    name: 'train',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'loop',
    cat: 'other',
    aliases: [],
  },
  {
    name: 'af',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'al',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'dz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ad',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ao',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ag',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ar',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'am',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'au',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'at',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'az',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bs',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bh',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bd',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bb',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'by',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'be',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bj',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bt',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bo',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ba',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'br',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bf',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bi',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kh',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ca',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cv',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cf',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'td',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'chile',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'co',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'km',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ci',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'hr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cy',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'congo',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'dk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'dj',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'dm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'do',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tl',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ec',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'eg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sv',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gq',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'er',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ee',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'et',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fj',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fi',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ga',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ge',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gh',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gd',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gt',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gy',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ht',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'hn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'hu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'is',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'in',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'indonesia',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ir',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'iq',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ie',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'il',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'jm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'jo',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ke',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ki',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'xk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'la',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lv',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lb',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ls',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ly',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'li',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lt',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'my',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mv',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ml',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mt',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mh',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mx',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'md',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mc',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'me',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ma',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'na',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'nr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'np',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'nl',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'nz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ni',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ne',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'nigeria',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kp',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'no',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'om',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pa',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'py',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pe',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ph',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pl',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pt',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'qa',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'cg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ro',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'rw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'kn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lc',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'vc',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ws',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'st',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'saudiarabia',
    cat: 'places',
    aliases: [':saudi:'],
  },
  {
    name: 'sn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'rs',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sc',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sl',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'si',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sb',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'so',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'za',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'lk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sd',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'se',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ch',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sy',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tj',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'th',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tg',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'to',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tt',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'turkmenistan',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'tuvalu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ug',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ua',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ae',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'uy',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'uz',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'vu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'va',
    cat: 'places',
    aliases: [],
  },
  {
    name: 've',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'vn',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'eh',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ye',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'zm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'zw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pr',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ky',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'bm',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'pf',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ps',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'nc',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'sh',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'aw',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'vi',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'hk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ac',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ms',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gl',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'nu',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'wf',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'mo',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fo',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'fk',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'je',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'ai',
    cat: 'places',
    aliases: [],
  },
  {
    name: 'gi',
    cat: 'places',
    aliases: [],
  },
]
