export default [
  'hideSidebar',
  'leaveChannel',
  'goToChannel',
  'kickMemberFromChannel',
  'showChannelMembersInvite',
  'loadSharedFiles',
  'loadMentions',
  'goToMessage',
  'searchMessages',
  'renameRoom',
  'setRoomDescription',
  'setRoomPrivacy',
  'setRoomColor',
  'setRoomIcon',
  'clearRoomRenameError',
  'showRoomDeteteDialog',
  'goToAddIntegrations'
]
