/**
 * Raw svg strings.
 */
export document from './svg/document.svg'
export pdf from './svg/pdf.svg'
export presentation from './svg/presentation.svg'
export link from './svg/link.svg'
export application from './svg/application.svg'
export file from './svg/file.svg'
export image from './svg/image.svg'
export spreadsheet from './svg/spreadsheet.svg'
export text from './svg/text.svg'
export video from './svg/video.svg'
export close from './svg/close.svg'
export skype from './svg/skype.svg'
export phone from './svg/phone.svg'
export envelope from './svg/envelope.svg'
export exit from './svg/exit.svg'
export invite from './svg/invite.svg'
export info from './svg/info.svg'
export at from './svg/at.svg'
export help from './svg/help.svg'
export sheet from './svg/sheet.svg'
export magnifier from './svg/magnifier.svg'
export comment from './svg/comment.svg'
export iconLink from './svg/icon-link.svg'
export user from './svg/user.svg'
export users from './svg/users.svg'

// Products.
export bitbucket from './svg/bitbucket.svg'
export box from './svg/box.svg'
export dropbox from './svg/dropbox.svg'
export evernote from './svg/evernote.svg'
export giphy from './svg/giphy.svg'
export imgur from './svg/imgur.svg'
export github from './svg/github.svg'
export googleCalendar from './svg/google-calendar.svg'
export googleDrive from './svg/google-drive.svg'
export grape from './svg/grape.svg'
export jira from './svg/jira.svg'
export pivotaltracker from './svg/pivotaltracker.svg'
export spotify from './svg/spotify.svg'
export stackoverflow from './svg/stackoverflow.svg'
export trello from './svg/trello.svg'
export wikipedia from './svg/wikipedia.svg'
export wordpress from './svg/wordpress.svg'
export youtube from './svg/youtube.svg'
