/**
 * Raw svg strings.
 */
export document from './svg/document.svg'
export pdf from './svg/pdf.svg'
export presentation from './svg/presentation.svg'
export link from './svg/link.svg'
export application from './svg/application.svg'
export file from './svg/file.svg'
export image from './svg/image.svg'
export spreadsheet from './svg/spreadsheet.svg'
export text from './svg/text.svg'
export video from './svg/video.svg'
export close from './svg/close.svg'
export skype from './svg/skype.svg'
export phone from './svg/phone.svg'
export envelope from './svg/envelope.svg'
export exit from './svg/exit.svg'
export invite from './svg/invite.svg'
export info from './svg/info.svg'
export at from './svg/at.svg'
export help from './svg/help.svg'
export sheet from './svg/sheet.svg'
export magnifier from './svg/magnifier.svg'
export comment from './svg/comment.svg'
export iconLink from './svg/icon-link.svg'
