import { zIndex } from '../../utils/z-index'

export default () => ({
  wrapper: {
    zIndex: zIndex('dialog'),
    position: 'absolute',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    animation: 'appearance 1s ease-in',
  },
  [`@keyframes appearance`]: {
    '0%': {
      opacity: 0,
    },
    '100%': {
      opacity: 1,
    },
  },
  background: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: zIndex('dialog'),
    left: 0,
    top: 0,
    background: '#333',
    opacity: '0.8',
  },
  dialog: {
    width: 360,
    height: 476,
    background: '#333',
    zIndex: zIndex('dialog'),
    borderRadius: 16,
    display: 'flex',
    flexDirection: 'column',
    position: 'absolute',
  },
  avatar: {
    margin: '40px auto',
    display: 'block',
    position: 'relative',
  },
  image: {
    height: 160,
    width: 160,
    borderRadius: '50%',
  },
  pulse: {
    position: 'absolute',
    width: 176,
    height: 176,
    display: 'block',
    top: -8,
    stroke: '#FFF',
    strokeWidth: 2,
    opacity: 1,
    transformOrigin: '50% 50%',
    animation: 'pulse 5s infinite cubic-bezier(0.6, 0, 0, 0.4)',
  },
  [`@keyframes pulse`]: {
    '0%': {
      strokeWidth: 2,
      strokeOpacity: 1,
      transform: 'scale(1)',
    },
    '50%': {
      strokeWidth: 2,
      strokeOpacity: 1,
      transform: 'scale(0.9)',
    },
    '100%': {
      strokeWidth: 2,
      strokeOpacity: 1,
      transform: 'scale(1)',
    },
  },
  name: {
    display: 'block',
    textAlign: 'center',
    fontSize: 23,
    fontWeight: 600,
    color: '#FFF',
  },
  incoming: {
    marginTop: 10,
    display: 'block',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: 600,
    color: '#FFF',
  },
  buttons: {
    marginTop: 60,
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    height: 64,
  },
  button: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    position: 'absolute',
    borderRadius: '50%',
  },
  reject: {
    width: 48,
    height: 48,
    background: '#FFF',
    left: 40,
  },
  missedIcon: {
    color: '#D4210A',
    width: 32,
    height: 12,
    pointerEvents: 'none',
  },
  accept: {
    width: 64,
    height: 64,
    background: '#6FA300',
    left: '50%',
    transform: 'translateX(-50%)',
  },
  ongoingIcon: {
    color: '#FFF',
    width: 32,
    height: 32,
    pointerEvents: 'none',
  },
})
